# This file is automatically generated. Do not edit!
# To re-generate, execute res/wrap/wrap.jl

using CEnum: CEnum, @cenum

@cenum MPSGraphTensorNamedDataLayout::UInt64 begin
    MPSGraphTensorNamedDataLayoutNCHW = 0x0000000000000000
    MPSGraphTensorNamedDataLayoutNHWC = 0x0000000000000001
    MPSGraphTensorNamedDataLayoutOIHW = 0x0000000000000002
    MPSGraphTensorNamedDataLayoutHWIO = 0x0000000000000003
    MPSGraphTensorNamedDataLayoutCHW = 0x0000000000000004
    MPSGraphTensorNamedDataLayoutHWC = 0x0000000000000005
    MPSGraphTensorNamedDataLayoutHW = 0x0000000000000006
    MPSGraphTensorNamedDataLayoutNCDHW = 0x0000000000000007
    MPSGraphTensorNamedDataLayoutNDHWC = 0x0000000000000008
    MPSGraphTensorNamedDataLayoutOIDHW = 0x0000000000000009
    MPSGraphTensorNamedDataLayoutDHWIO = 0x000000000000000a
end

@cenum MPSGraphPaddingStyle::UInt64 begin
    MPSGraphPaddingStyleExplicit = 0x0000000000000000
    MPSGraphPaddingStyleTF_VALID = 0x0000000000000001
    MPSGraphPaddingStyleTF_SAME = 0x0000000000000002
    MPSGraphPaddingStyleExplicitOffset = 0x0000000000000003
    MPSGraphPaddingStyleONNX_SAME_LOWER = 0x0000000000000004
end

@cenum MPSGraphPaddingMode::Int64 begin
    MPSGraphPaddingModeConstant = 0
    MPSGraphPaddingModeReflect = 1
    MPSGraphPaddingModeSymmetric = 2
    MPSGraphPaddingModeClampToEdge = 3
    MPSGraphPaddingModeZero = 4
    MPSGraphPaddingModePeriodic = 5
    MPSGraphPaddingModeAntiPeriodic = 6
end

@cenum MPSGraphReductionMode::UInt64 begin
    MPSGraphReductionModeMin = 0x0000000000000000
    MPSGraphReductionModeMax = 0x0000000000000001
    MPSGraphReductionModeSum = 0x0000000000000002
    MPSGraphReductionModeProduct = 0x0000000000000003
    MPSGraphReductionModeArgumentMin = 0x0000000000000004
    MPSGraphReductionModeArgumentMax = 0x0000000000000005
end

@cenum MPSGraphDeviceType::UInt32 begin
    MPSGraphDeviceTypeMetal = 0x0000000000000000
end

@cenum MPSGraphOptions::UInt64 begin
    MPSGraphOptionsNone = 0x0000000000000000
    MPSGraphOptionsSynchronizeResults = 0x0000000000000001
    MPSGraphOptionsVerbose = 0x0000000000000002
    MPSGraphOptionsDefault = 0x0000000000000001
end

@cenum MPSGraphOptimization::UInt64 begin
    MPSGraphOptimizationLevel0 = 0x0000000000000000
    MPSGraphOptimizationLevel1 = 0x0000000000000001
end

@cenum MPSGraphOptimizationProfile::UInt64 begin
    MPSGraphOptimizationProfilePerformance = 0x0000000000000000
    MPSGraphOptimizationProfilePowerEfficiency = 0x0000000000000001
end

@cenum MPSGraphExecutionStage::UInt64 begin
    MPSGraphExecutionStageCompleted = 0x0000000000000000
end

@cenum MPSGraphDeploymentPlatform::UInt64 begin
    MPSGraphDeploymentPlatformMacOS = 0x0000000000000000
    MPSGraphDeploymentPlatformIOS = 0x0000000000000001
    MPSGraphDeploymentPlatformTvOS = 0x0000000000000002
    MPSGraphDeploymentPlatformVisionOS = 0x0000000000000003
end

@cenum MPSGraphFFTScalingMode::UInt64 begin
    MPSGraphFFTScalingModeNone = 0x0000000000000000
    MPSGraphFFTScalingModeSize = 0x0000000000000001
    MPSGraphFFTScalingModeUnitary = 0x0000000000000002
end

@cenum MPSGraphLossReductionType::UInt64 begin
    MPSGraphLossReductionTypeNone = 0x0000000000000000
    MPSGraphLossReductionTypeAxis = 0x0000000000000000
    MPSGraphLossReductionTypeSum = 0x0000000000000001
    MPSGraphLossReductionTypeMean = 0x0000000000000002
end

@cenum MPSGraphNonMaximumSuppressionCoordinateMode::UInt64 begin
    MPSGraphNonMaximumSuppressionCoordinateModeCornersHeightFirst = 0x0000000000000000
    MPSGraphNonMaximumSuppressionCoordinateModeCornersWidthFirst = 0x0000000000000001
    MPSGraphNonMaximumSuppressionCoordinateModeCentersHeightFirst = 0x0000000000000002
    MPSGraphNonMaximumSuppressionCoordinateModeCentersWidthFirst = 0x0000000000000003
end

@cenum MPSGraphPoolingReturnIndicesMode::UInt64 begin
    MPSGraphPoolingReturnIndicesNone = 0x0000000000000000
    MPSGraphPoolingReturnIndicesGlobalFlatten1D = 0x0000000000000001
    MPSGraphPoolingReturnIndicesGlobalFlatten2D = 0x0000000000000002
    MPSGraphPoolingReturnIndicesGlobalFlatten3D = 0x0000000000000003
    MPSGraphPoolingReturnIndicesGlobalFlatten4D = 0x0000000000000004
    MPSGraphPoolingReturnIndicesLocalFlatten1D = 0x0000000000000005
    MPSGraphPoolingReturnIndicesLocalFlatten2D = 0x0000000000000006
    MPSGraphPoolingReturnIndicesLocalFlatten3D = 0x0000000000000007
    MPSGraphPoolingReturnIndicesLocalFlatten4D = 0x0000000000000008
end

@cenum MPSGraphRandomDistribution::UInt64 begin
    MPSGraphRandomDistributionUniform = 0x0000000000000000
    MPSGraphRandomDistributionNormal = 0x0000000000000001
    MPSGraphRandomDistributionTruncatedNormal = 0x0000000000000002
end

@cenum MPSGraphRandomNormalSamplingMethod::UInt64 begin
    MPSGraphRandomNormalSamplingInvCDF = 0x0000000000000000
    MPSGraphRandomNormalSamplingBoxMuller = 0x0000000000000001
end

@cenum MPSGraphResizeMode::UInt64 begin
    MPSGraphResizeNearest = 0x0000000000000000
    MPSGraphResizeBilinear = 0x0000000000000001
end

@cenum MPSGraphResizeNearestRoundingMode::UInt64 begin
    MPSGraphResizeNearestRoundingModeRoundPreferCeil = 0x0000000000000000
    MPSGraphResizeNearestRoundingModeRoundPreferFloor = 0x0000000000000001
    MPSGraphResizeNearestRoundingModeCeil = 0x0000000000000002
    MPSGraphResizeNearestRoundingModeFloor = 0x0000000000000003
    MPSGraphResizeNearestRoundingModeRoundToEven = 0x0000000000000004
    MPSGraphResizeNearestRoundingModeRoundToOdd = 0x0000000000000005
end

@cenum MPSGraphRNNActivation::UInt64 begin
    MPSGraphRNNActivationNone = 0x0000000000000000
    MPSGraphRNNActivationRelu = 0x0000000000000001
    MPSGraphRNNActivationTanh = 0x0000000000000002
    MPSGraphRNNActivationSigmoid = 0x0000000000000003
    MPSGraphRNNActivationHardSigmoid = 0x0000000000000004
end

@cenum MPSGraphScatterMode::Int64 begin
    MPSGraphScatterModeAdd = 0
    MPSGraphScatterModeSub = 1
    MPSGraphScatterModeMul = 2
    MPSGraphScatterModeDiv = 3
    MPSGraphScatterModeMin = 4
    MPSGraphScatterModeMax = 5
    MPSGraphScatterModeSet = 6
end

@cenum MPSGraphSparseStorageType::UInt64 begin
    MPSGraphSparseStorageCOO = 0x0000000000000000
    MPSGraphSparseStorageCSC = 0x0000000000000001
    MPSGraphSparseStorageCSR = 0x0000000000000002
end
